-- Deploy omlpi:0001-data to pg
-- requires: 0000-locales

BEGIN;

CREATE TABLE area (
    id INT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO area (id, name) VALUES (1, 'Assistência Social'), (2, 'Educação'), (3, 'Saúde');

CREATE TABLE indicator (
    id          INT PRIMARY KEY,
    description TEXT NOT NULL UNIQUE,
    area_id     INT NOT NULL REFERENCES area(id),
    base        TEXT
);

--CREATE TABLE subindicator_category (
--    id INT PRIMARY KEY,
--    name TEXT NOT NULL
--);

CREATE TABLE subindicator (
    id INT NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    classification TEXT NOT NULL,
    UNIQUE(description)
    --subindicator_category_id INT NOT NULL REFERENCES subindicator_category(id)
);

CREATE TABLE indicator_locale (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_id INT NOT NULL REFERENCES indicator(id),
    value_relative TEXT NOT NULL,
    value_absolute TEXT NOT NULL
);

CREATE TABLE subindicator_locale (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_id INT NOT NULL REFERENCES indicator(id),
    subindicator_id INT NOT NULL REFERENCES subindicator(id),
    value_relative TEXT NOT NULL,
    value_absolute TEXT NOT NULL
);

--CREATE TABLE data (
--    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    locale_id INT NOT NULL REFERENCES locale(id),
--    indicator_id INT NOT NULL REFERENCES indicator(id),
--    subindicator_id INT,
--    year INT NOT NULL,
--    area_id INT NOT NULL REFERENCES area(id),
--    FOREIGN KEY (indicator_id, subindicator_id) REFERENCES subindicator(indicator_id, id)
--);

COMMIT;
