swagger: "2.0"
info:
  description: 'The backend of the OMLPL project'
  version: 0.1.2
  title: OMLPL API
  contact:
    email: carlos@appcivico.com
  license:
    name: Affero GPL
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'

host: dev-omlpi-api.appcivico.com
basePath: /v1
schemes:
  - https
produces:
  - application/json

tags:
  - name: areas
    description: All about the thematic axis
  - name: locales
    description: Retrieve data from a specific locale

paths:
  /areas:
    get:
      x-mojo-to: 'areas#list'
      operationId: listAreas
      tags:
        - areas
      summary: List all thematic axis
      responses:
        200:
          description: List of areas
          schema:
            $ref: '#/definitions/Areas'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /locales:
    get:
      x-mojo-to: 'locales#list'
      operationId: listLocales
      tags:
        - locales
      summary: List all available locales
      responses:
        200:
          description: List locales
          schema:
            $ref: '#/definitions/Locales'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /locales/{locale_id}:
    get:
      operationId: showLocaleById
      x-mojo-to: 'locales#read'
      summary: Retrieve data from the locales
      tags:
        - locales
      parameters:
        - name: locale_id
          in: path
          required: true
          description: The id of the locale to retrieve
          type: integer
        - name: area_id
          in: query
          description: Filter data by an area
          required: false
          type: integer
      responses:
        200:
          description: Info for a specific locale
          schema:
            $ref: '#/definitions/Locale'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Areas:
    type: object
    properties:
      areas:
        type: array
        items:
          $ref: '#/definitions/Area'
  Area:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  Locale:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: string
        enum:
          - country
          - region
          - state
          - city
  Locales:
    type: object
    properties:
      locales:
        type: array
        items:
          $ref: '#/definitions/Locale'
  Error:
    type: "object"
    required:
      - error
      - message
    properties:
      error:
        type: string
        enum:
          - page_not_found
          - permission_denied
          - method_not_allowed
          - internal_server_error
      message:
        type: string