swagger: '2.0'
info:
  description: 'The backend of the OMLPL project'
  version: 1.0.0
  title: OMLPL API
  contact:
    email: carlos@appcivico.com
  license:
    name: Affero GPL
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'

tags:
  - name: areas
    description: All about the thematic axis
schemes:
  - https
paths:
  /areas:
    get:
      x-mojo-to: 'areas#list'
      operationId: list
      tags:
        - areas
      summary: List all thematic axis
      produces:
        - application/json
      responses:
        200:
          description: List of areas
          schema:
            type: object
definitions:
  Area:
    type: object
    properties:
      id:
        type: integer
      name:
        type: integer
        format: string
    xml:
      name: Area
  Locale:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: string
        enum:
          - country
          - region
          - state
          - city
    xml:
      name: Locale