swagger: "2.0"
info:
  description: 'The backend of the OMLPL project'
  version: 1.0.0
  title: OMLPL API
  contact:
    email: carlos@appcivico.com
  license:
    name: Affero GPL
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'

host: dev-omlpi.appcivico.com
schemes:
  - https
produces:
  - application/json

tags:
  - name: areas
    description: All about the thematic axis
  - name: locales
    description: Retrieve data from the locales

paths:
  /areas:
    get:
      x-mojo-to: 'areas#list'
      operationId: listAreas
      tags:
        - areas
      summary: List all thematic axis
      responses:
        200:
          description: List of areas
          schema:
            $ref: '#/definitions/Area'
  /locales:
    get:
      x-mojo-to: 'locales#list'
      operationId: listLocales
      tags:
        - locales
      summary: List all locales
      responses:
        200:
          description: List of available locales
          schema:
            $ref: '#/definitions/Locale'

definitions:
  Area:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  Locale:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: string
        enum:
          - country
          - region
          - state
          - city